# from api import *
# from kubectl_build import *

load('../Tiltfile', 'kubectl_build')

allow_k8s_contexts(['contabo'])

k8s_yaml('deployment.yml')
kubectl_build('cr.ixk.me/syfxlin/demo', registry_secret='devspace-auth-cr-ixk-me')
