# from kubectl_build import *
# from docker_nginx import *

load('../../kubectl_build/Tiltfile', 'kubectl_build')
load('../Tiltfile', 'docker_nginx')

allow_k8s_contexts(['contabo'])

k8s_yaml('deployment.yml')
kubectl_build('cr.ixk.me/syfxlin/demo', dockerfile_contents=docker_nginx(), registry_secret='devspace-auth-cr-ixk-me')
